version: "2.3"
services:
  database:
    image: "angelfernandezf/xovetic-lba-database:1.0.0"
    mem_limit: 256M
    restart: unless-stopped
    environment:
      - POSTGRES_USER=lba
      - POSTGRES_PASSWORD=lb4Us3r
      - POSTGRES_DB=lba
      - POSTGRES_PORT=5432
    networks:
      lba-network:
        aliases:
          - lbadb
    ports:
      - 5432:5432
    volumes:
      - lba-db-volume:/var/lib/postgresql/data
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"

  teams:
    image: "angelfernandezf/xovetic-lba-teams:1.0.0"
    mem_limit: 128M
    restart: unless-stopped
    environment:
      - JAVA_XMS=128
      - JAVA_XMX=512
      - SPRING_DATASOURCE_USERNAME=lba
      - SPRING_DATASOURCE_PASSWORD=lb4Us3r
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lbadb:5432/lba?currentSchema=teams
    depends_on:
      - database
    networks:
      lba-network:
        aliases:
          - lbateams
    ports:
      - 81:8080
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"

  players:
    image: "angelfernandezf/xovetic-lba-players:1.0.0"
    mem_limit: 128M
    restart: unless-stopped
    environment:
      - JAVA_XMS=128
      - JAVA_XMX=512
      - SPRING_DATASOURCE_USERNAME=lba
      - SPRING_DATASOURCE_PASSWORD=lb4Us3r
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lbadb:5432/lba?currentSchema=players
    depends_on:
      - database
    networks:
      lba-network:
        aliases:
          - lbaplayers
    ports:
      - 82:8080
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"
networks:
  lba-network:
    driver: bridge

volumes:
  lba-db-volume: