version: "2.3"
services:
  database:
    image: "angelfernandezf/xovetic-lba-database:$DATABASE_VERSION"
    mem_limit: 256M
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=lba
      - POSTGRES_PORT=5432
    networks:
      lba-network:
        aliases:
          - lbadb
    volumes:
      - lba-db-volume:/var/lib/postgresql/data
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"

  registry:
    image: "angelfernandezf/xovetic-lba-registry:$REGISTRY_VERSION"
    mem_limit: 256M
    restart: unless-stopped
    networks:
      lba-network:
        aliases:
          - lbaregistry
          - eureka
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"

  apigateway:
    image: "angelfernandezf/xovetic-lba-apigateway:$GATEWAY_VERSION"
    mem_limit: 256M
    restart: unless-stopped
    networks:
      lba-network:
        aliases:
          - lbaapigateway
    ports:
      - 2020:8080
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"

  teams:
    image: "angelfernandezf/xovetic-lba-teams:$TEAMS_VERSION"
    mem_limit: 128M
    restart: unless-stopped
    environment:
      - JAVA_XMS=128
      - JAVA_XMX=512
      - SPRING_DATASOURCE_USERNAME=$DATABASE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD
      - SPRING_DATASOURCE_URL=${DATABASE_URL}?currentSchema=teams
    depends_on:
      - database
      - registry
    networks:
      lba-network:
        aliases:
          - lbateams
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"

  players:
    image: "angelfernandezf/xovetic-lba-players:$PLAYERS_VERSION"
    mem_limit: 128M
    restart: unless-stopped
    environment:
      - JAVA_XMS=128
      - JAVA_XMX=512
      - SPRING_DATASOURCE_USERNAME=$DATABASE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD
      - SPRING_DATASOURCE_URL=${DATABASE_URL}?currentSchema=players
    depends_on:
      - database
      - registry
    networks:
      lba-network:
        aliases:
          - lbaplayers
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "30m"
networks:
  lba-network:
    driver: bridge

volumes:
  lba-db-volume: